name: thebrainhub
favicon: null
layout_spectrum: 0.3810474940109998
typography_spectrum: 0.45756635651923716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0073313238099217415
  lightness: 0.1815518292132765
  saturation: 0.3317992629017681
  rhythmicContrast: 0.17153429007157683
purpose: []
